name = "PSID"
uuid = "92fd0282-be9c-47fb-a489-f0d0a91db595"
version = "1.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONTables = "b9914132-a727-11e9-1322-f18e41205b0b"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AbstractTrees = "0.2.1, 0.3"
CSV = "0.5.16, 0.6, 0.7"
DataDeps = "0.7.0"
DataFrames = "0.20.0, 0.21"
DataFramesMeta = "0.5.0"
DataStructures = "0.17.5, 0.18"
JSON3 = "= 0.1.12, 1.0"
JSONTables = "0.1.3, 1.0"
LightXML = "0.8.1, 0.9"
Parsers = "0.3, 1.0"
XLSX = "0.5.8, 0.6, 0.7"
julia = "1.1"
